// Code generated by sqlc. DO NOT EDIT.
// source: example.sql

package db

import (
	"context"
)

const createExample = `-- name: CreateExample :one
INSERT INTO example (
  usecase_id,
  sentence
) VALUES (
  $1,
  $2
)
RETURNING id, usecase_id, sentence
`

type CreateExampleParams struct {
	UsecaseID int64  `json:"usecase_id"`
	Sentence  string `json:"sentence"`
}

func (q *Queries) CreateExample(ctx context.Context, arg CreateExampleParams) (Example, error) {
	row := q.db.QueryRowContext(ctx, createExample, arg.UsecaseID, arg.Sentence)
	var i Example
	err := row.Scan(&i.ID, &i.UsecaseID, &i.Sentence)
	return i, err
}

const listExampleByUsecase = `-- name: ListExampleByUsecase :many
SELECT id, usecase_id, sentence FROM example
WHERE usecase_id = $1
`

func (q *Queries) ListExampleByUsecase(ctx context.Context, usecaseID int64) ([]Example, error) {
	rows, err := q.db.QueryContext(ctx, listExampleByUsecase, usecaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Example
	for rows.Next() {
		var i Example
		if err := rows.Scan(&i.ID, &i.UsecaseID, &i.Sentence); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
