// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Example struct {
	ID        int64  `json:"id"`
	UsecaseID int64  `json:"usecase_id"`
	Sentence  string `json:"sentence"`
}

type Usecase struct {
	ID                  int64  `json:"id"`
	WordID              int64  `json:"word_id"`
	DescriptionSentence string `json:"description_sentence"`
}

type User struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	Password          string    `json:"password"`
	LatestVisit       time.Time `json:"latest_visit"`
	StudyAmount       int32     `json:"study_amount"`
	StudyGoal         int32     `json:"study_goal"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}

type Word struct {
	ID       int64  `json:"id"`
	Spelling string `json:"spelling"`
}

type Writing struct {
	ID        int64     `json:"id"`
	Writing   string    `json:"writing"`
	UsecaseID int64     `json:"usecase_id"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}
