// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CountAllExample(ctx context.Context) (int64, error)
	CountAllUsecase(ctx context.Context) (int64, error)
	CountAllWord(ctx context.Context) (int64, error)
	DeleteAllExample(ctx context.Context) error
	DeleteAllUsecase(ctx context.Context) error
	DeleteAllWord(ctx context.Context) error
	GetUsecaseById(ctx context.Context, id int64) (Usecase, error)
	GetUsecaseByWord(ctx context.Context, wordID int64) ([]Usecase, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetWordById(ctx context.Context, id int64) (Word, error)
	GetWordByPage(ctx context.Context, arg GetWordByPageParams) ([]Word, error)
	GetWordBySpelling(ctx context.Context, spelling string) (Word, error)
	GetWords(ctx context.Context, arg GetWordsParams) ([]Word, error)
	InsertExample(ctx context.Context, arg InsertExampleParams) (Example, error)
	InsertUsecase(ctx context.Context, arg InsertUsecaseParams) (Usecase, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	InsertWord(ctx context.Context, arg InsertWordParams) (Word, error)
	ListExampleByUsecase(ctx context.Context, usecaseID int64) ([]Example, error)
}

var _ Querier = (*Queries)(nil)
