// Code generated by sqlc. DO NOT EDIT.
// source: writing.sql

package db

import (
	"context"
	"time"
)

const countWritingsGroupByCreateAt = `-- name: CountWritingsGroupByCreateAt :many
SELECT EXTRACT (DAY FROM created_at) as Day, COUNT(user_id) as Count 
FROM 
(SELECT id, writing, usecase_id, user_id, created_at FROM writing 
ORDER BY EXTRACT (MONTH FROM created_at) ASC, EXTRACT (DAY FROM created_at) ASC
) AS ordered_table
WHERE user_id = $1 
AND created_at >= $2 
AND created_at <= $3
GROUP BY EXTRACT (DAY FROM created_at)
`

type CountWritingsGroupByCreateAtParams struct {
	UserID      int64     `json:"user_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type CountWritingsGroupByCreateAtRow struct {
	Day   float64 `json:"day"`
	Count int64   `json:"count"`
}

func (q *Queries) CountWritingsGroupByCreateAt(ctx context.Context, arg CountWritingsGroupByCreateAtParams) ([]CountWritingsGroupByCreateAtRow, error) {
	rows, err := q.db.QueryContext(ctx, countWritingsGroupByCreateAt, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountWritingsGroupByCreateAtRow{}
	for rows.Next() {
		var i CountWritingsGroupByCreateAtRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteWriting = `-- name: DeleteWriting :exec
DELETE FROM writing WHERE id = $1
`

func (q *Queries) DeleteWriting(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWriting, id)
	return err
}

const getWritingsById = `-- name: GetWritingsById :one
SELECT id, writing, usecase_id, user_id, created_at FROM writing WHERE id = $1
`

func (q *Queries) GetWritingsById(ctx context.Context, id int64) (Writing, error) {
	row := q.db.QueryRowContext(ctx, getWritingsById, id)
	var i Writing
	err := row.Scan(
		&i.ID,
		&i.Writing,
		&i.UsecaseID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getWritingsByUserIdAndUsecaseId = `-- name: GetWritingsByUserIdAndUsecaseId :many
SELECT id, writing, usecase_id, user_id, created_at FROM writing WHERE user_id = $1 AND usecase_id = $2
`

type GetWritingsByUserIdAndUsecaseIdParams struct {
	UserID    int64 `json:"user_id"`
	UsecaseID int64 `json:"usecase_id"`
}

func (q *Queries) GetWritingsByUserIdAndUsecaseId(ctx context.Context, arg GetWritingsByUserIdAndUsecaseIdParams) ([]Writing, error) {
	rows, err := q.db.QueryContext(ctx, getWritingsByUserIdAndUsecaseId, arg.UserID, arg.UsecaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Writing{}
	for rows.Next() {
		var i Writing
		if err := rows.Scan(
			&i.ID,
			&i.Writing,
			&i.UsecaseID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWriting = `-- name: InsertWriting :one
INSERT INTO writing (
  writing,
  usecase_id,
  user_id
) VALUES (
  $1,
  $2,
  $3
)
RETURNING id, writing, usecase_id, user_id, created_at
`

type InsertWritingParams struct {
	Writing   string `json:"writing"`
	UsecaseID int64  `json:"usecase_id"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) InsertWriting(ctx context.Context, arg InsertWritingParams) (Writing, error) {
	row := q.db.QueryRowContext(ctx, insertWriting, arg.Writing, arg.UsecaseID, arg.UserID)
	var i Writing
	err := row.Scan(
		&i.ID,
		&i.Writing,
		&i.UsecaseID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
